holdings:
- symbol: '588080'
  market: ETF
  shares: 70100
  cost_price: 1.413
  buy_date: '2026-02-16'
- symbol: '518880'
  market: ETF
  shares: 3000
  cost_price: -5.239
  buy_date: '2026-02-16'
- symbol: '513500'
  market: ETF
  shares: 56600
  cost_price: 2.03
  buy_date: '2026-02-16'
risk:
  stop_loss: 0.08
  take_profit: 0.2
  position_warning: 0.3
analysis:
  default_strategies:
  - ma_cross
  - macd
  - rsi
  - bollinger
  - multi_factor
